apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bs8y1cybg-nodejs
  janus-idp.io/tekton: bs8y1cybg-nodejs
  backstage.io/kubernetes-id: bs8y1cybg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bs8y1cybg-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
