apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bs8y1cybg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bs8y1cybg-nodejs 
  name: bs8y1cybg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bs8y1cybg-nodejs 
